{
 "title": "Pod JVM 监控",
 "description": "jmx exporter monitor",
 "tags": [
  "jmx",
  "JVM",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "服务名", "query": { "query": "label_values(jvm_info, job)" } },
   {
    "name": "app",
    "label": "实例",
    "query": {
     "query": "label_values(up{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(up{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "memarea",
    "query": {
     "query": "label_values(jvm_memory_bytes_used{job=\"$job\", instance=\"$app$node\"}, area)"
    }
   },
   {
    "name": "mempool",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_max{job=\"$job\", instance=\"$app$node\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"$job\", instance=\"$app\"}",
     "legendFormat": "State"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\", instance=\"$app\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_available_processors{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "CPU Cores"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "os_total_physical_memory_size{job=\"$job\", instance=\"$app$node\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Total RAM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cpu Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuTime{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "Process"
    },
    {
     "expr": "java_lang_Threading_CurrentThreadCpuTime{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "Current Thread"
    },
    {
     "expr": "process_cpu_seconds_total{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "Total Spent"
    }
   ]
  },
  {
   "title": "CPU Process Load (1m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(os_process_cpu_load{job=\"$job\", instance=\"$app$node\"}[1m]) * 100",
     "legendFormat": "CPU Process Load (1m avg)"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(os_system_cpu_load{job=\"$job\", instance=\"$app$node\"}[1m]) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "CPU System Load (1m avg)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU System load average",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "os_system_cpu_load{job=\"$job\", instance=\"$app$node\"} * 100",
     "legendFormat": "CPU System load average"
    }
   ]
  },
  {
   "title": "JDK",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 4 },
   "targets": [
    {
     "expr": "label_join(jvm_info{job=\"$job\", instance=\"$app$node\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "os_system_cpu_load{job=\"$job\", instance=\"$app\"}",
     "legendFormat": "System"
    },
    {
     "expr": "os_process_cpu_load{job=\"$job\", instance=\"$app\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\", instance=\"$app\"}",
     "legendFormat": "Descriptors"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Physical memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "os_free_physical_memory_size{job=\"$job\", instance=\"$app\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "os_total_physical_memory_size{job=\"$job\", instance=\"$app\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "os_committed_virtual_memory_size{job=\"$job\", instance=\"$app\"}",
     "legendFormat": "Committed VM"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\", instance=\"$app\"}",
     "legendFormat": "Resident"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\", instance=\"$app\"}",
     "legendFormat": "Virtual"
    }
   ]
  },
  { "title": "Memory JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "JVM Memory Used [$memarea]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=~\"$memarea\",job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_bytes_max{area=~\"$memarea\",job=\"$job\",instance=\"$app$node\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "JVM Memory Usage [$memarea]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",job=\"$job\", instance=\"$app$node\"} / ignoring(area) group_left java_lang_OperatingSystem_TotalPhysicalMemorySize{job=\"$job\", instance=\"$app$node\"} *100",
     "legendFormat": "System"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",job=\"$job\", instance=\"$app$node\"} / (jvm_memory_bytes_max{area=\"$memarea\", job=\"$job\",instance=\"$app$node\"} >=0) *100",
     "legendFormat": "JVM"
    }
   ]
  },
  {
   "title": "JVM Memory committed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Memory JVM Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true
  },
  {
   "title": "Memory pool [$mempool]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "repeat": "mempool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=~\"$mempool\",job=\"$job\",instance=\"$app$node\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=~\"$mempool\",job=\"$job\",instance=\"$app$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=~\"$mempool\",job=\"$job\",instance=\"$app$node\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "GC count increase",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC Time rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC Time increase",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "Threading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "jvm_threads_daemon{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_deadlocked{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "Deadlocked"
    },
    {
     "expr": "jvm_threads_deadlocked_monitor{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "Deadlocked monitor"
    },
    {
     "expr": "jvm_threads_peak{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "Peak"
    },
    {
     "expr": "jvm_threads_started_total{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "Started Total"
    }
   ]
  },
  {
   "title": "JVM Threads count increase",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(jvm_threads_current{job=\"$job\", instance=\"$app\"}[$__interval])",
     "legendFormat": "Current"
    },
    {
     "expr": "increase(jvm_threads_daemon{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "Daemon"
    },
    {
     "expr": "increase(jvm_threads_peak{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "JVM Threads count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_daemon{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "jvm_threads_daemon{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_peak{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "Peak"
    },
    {
     "expr": "jvm_threads_started_total{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "Started"
    }
   ]
  },
  {
   "title": "JVM Threads increase",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "increase(jvm_threads_current{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "Current"
    },
    {
     "expr": "increase(jvm_threads_daemon{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "Daemon"
    },
    {
     "expr": "increase(jvm_threads_deadlocked{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "Deadlocked"
    },
    {
     "expr": "increase(jvm_threads_deadlocked_monitor{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "Deadlocked monitor"
    },
    {
     "expr": "increase(jvm_threads_peak{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "Peak"
    },
    {
     "expr": "increase(jvm_threads_started_total{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "Started Total"
    }
   ]
  },
  { "title": "Classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Classes Loaded increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(jvm_classes_loaded{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "currently"
    },
    {
     "expr": "increase(jvm_classes_loaded_total{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "currently"
    },
    {
     "expr": "jvm_classes_loaded_total{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "total"
    }
   ]
  }
 ]
}